// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./employee/Navbar"; // Import your Navbar here

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Global navigation links for ALL pages
    const navLinks = [
        { name: "Home", href: "/" },
        { name: "Employee Form", href: "/employee/employee-form" },
        { name: "Settings", href: "/settings" },
    ];

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                {/* Render the Navbar here once for all pages */}
                <Navbar brand="EMS Portal" links={navLinks} />
                <main className="flex-1 p-6">{children}</main>
            </body>
        </html>
    );
}
